"""add surveyor_number

Revision ID: 3063613e7747
Revises: 6910c2e12faf
Create Date: 2026-07-18 01:00:12.986976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3063613e7747'
down_revision: Union[str, None] = '6910c2e12faf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('surveyors', sa.Column('surveyor_number', sa.Text(), nullable=True))
    op.create_unique_constraint(None, 'surveyors', ['surveyor_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'surveyors', type_='unique')
    op.drop_column('surveyors', 'surveyor_number')
    # ### end Alembic commands ###
