"""add report_due_days to survey_types

Revision ID: 3bd91e62cd11
Revises: 3063613e7747
Create Date: 2026-07-19 15:46:39.151519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bd91e62cd11'
down_revision: Union[str, None] = '3063613e7747'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey_types', sa.Column('report_due_days', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('survey_types', 'report_due_days')
    # ### end Alembic commands ###
