"""initial schema

Revision ID: 6910c2e12faf
Revises: 
Create Date: 2026-07-17 23:48:15.465536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6910c2e12faf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('address_line_1', sa.Text(), nullable=True),
    sa.Column('address_line_2', sa.Text(), nullable=True),
    sa.Column('town', sa.Text(), nullable=True),
    sa.Column('county', sa.Text(), nullable=True),
    sa.Column('postcode', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address_line_1', sa.Text(), nullable=False),
    sa.Column('address_line_2', sa.Text(), nullable=True),
    sa.Column('town', sa.Text(), nullable=False),
    sa.Column('county', sa.Text(), nullable=True),
    sa.Column('postcode', sa.Text(), nullable=False),
    sa.Column('outward_code', sa.Text(), sa.Computed("UPPER(SPLIT_PART(postcode, ' ', 1))", persisted=True), nullable=True),
    sa.Column('property_type', sa.Text(), nullable=True),
    sa.Column('tenure', sa.Text(), nullable=True),
    sa.Column('num_bedrooms', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('survey_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('surveyors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.Text(), nullable=False),
    sa.Column('last_name', sa.Text(), nullable=False),
    sa.Column('company_name', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('phone', sa.Text(), nullable=False),
    sa.Column('rics_number', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('role', sa.Text(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('surveyor_coverage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('surveyor_id', sa.Integer(), nullable=False),
    sa.Column('outward_code', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['surveyor_id'], ['surveyors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('surveyor_id', 'outward_code')
    )
    op.create_table('surveyor_qualifications',
    sa.Column('surveyor_id', sa.Integer(), nullable=False),
    sa.Column('survey_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['survey_type_id'], ['survey_types.id'], ),
    sa.ForeignKeyConstraint(['surveyor_id'], ['surveyors.id'], ),
    sa.PrimaryKeyConstraint('surveyor_id', 'survey_type_id')
    )
    op.create_table('instructions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('our_ref', sa.Text(), nullable=False),
    sa.Column('client_ref', sa.Text(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('survey_type_id', sa.Integer(), nullable=False),
    sa.Column('borrower_name', sa.Text(), nullable=False),
    sa.Column('borrower_phone', sa.Text(), nullable=True),
    sa.Column('borrower_email', sa.Text(), nullable=True),
    sa.Column('assigned_surveyor_id', sa.Integer(), nullable=True),
    sa.Column('agreed_client_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('agreed_surveyor_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.Enum('received', 'surveyor_assigned', 'booked', 'inspection_complete', 'report_received', 'invoiced', 'complete', 'on_hold', 'cancelled', name='instruction_status'), nullable=False),
    sa.Column('received_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('inspection_date', sa.Date(), nullable=True),
    sa.Column('report_due_date', sa.Date(), nullable=True),
    sa.Column('report_received_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('invoiced_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('completed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('priority', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['assigned_surveyor_id'], ['surveyors.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['client_contacts.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['survey_type_id'], ['survey_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('our_ref')
    )
    op.create_table('instruction_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instruction_id', sa.Integer(), nullable=False),
    sa.Column('old_status', sa.Enum('received', 'surveyor_assigned', 'booked', 'inspection_complete', 'report_received', 'invoiced', 'complete', 'on_hold', 'cancelled', name='instruction_status'), nullable=True),
    sa.Column('new_status', sa.Enum('received', 'surveyor_assigned', 'booked', 'inspection_complete', 'report_received', 'invoiced', 'complete', 'on_hold', 'cancelled', name='instruction_status'), nullable=False),
    sa.Column('changed_by', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('changed_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['instruction_id'], ['instructions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('instruction_status_history')
    op.drop_table('instructions')
    op.drop_table('surveyor_qualifications')
    op.drop_table('surveyor_coverage')
    op.drop_table('client_contacts')
    op.drop_table('surveyors')
    op.drop_table('survey_types')
    op.drop_table('properties')
    op.drop_table('clients')
    # ### end Alembic commands ###
