"""add distance_band to surveyor_coverage

Revision ID: 711fb21f9064
Revises: c8721bfd59e5
Create Date: 2026-07-20 17:55:36.080226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '711fb21f9064'
down_revision: Union[str, None] = 'c8721bfd59e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('surveyor_coverage', sa.Column('distance_band', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('surveyor_coverage', 'distance_band')
    # ### end Alembic commands ###
