"""surveyor new fields and client exclusions

Revision ID: c8721bfd59e5
Revises: 3bd91e62cd11
Create Date: 2026-07-20 12:59:01.356263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8721bfd59e5'
down_revision: Union[str, None] = '3bd91e62cd11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('surveyor_client_exclusions',
    sa.Column('surveyor_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['surveyor_id'], ['surveyors.id'], ),
    sa.PrimaryKeyConstraint('surveyor_id', 'client_id')
    )
    op.add_column('surveyors', sa.Column('personal_phone', sa.Text(), nullable=True))
    op.add_column('surveyors', sa.Column('pi_cover_amount', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('surveyors', sa.Column('office_address_line_1', sa.Text(), nullable=True))
    op.add_column('surveyors', sa.Column('office_address_line_2', sa.Text(), nullable=True))
    op.add_column('surveyors', sa.Column('office_town', sa.Text(), nullable=True))
    op.add_column('surveyors', sa.Column('office_county', sa.Text(), nullable=True))
    op.add_column('surveyors', sa.Column('office_postcode', sa.Text(), nullable=True))
    op.add_column('surveyors', sa.Column('firm_type', sa.Text(), nullable=True))
    op.add_column('surveyors', sa.Column('num_partners', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('surveyors', 'num_partners')
    op.drop_column('surveyors', 'firm_type')
    op.drop_column('surveyors', 'office_postcode')
    op.drop_column('surveyors', 'office_county')
    op.drop_column('surveyors', 'office_town')
    op.drop_column('surveyors', 'office_address_line_2')
    op.drop_column('surveyors', 'office_address_line_1')
    op.drop_column('surveyors', 'pi_cover_amount')
    op.drop_column('surveyors', 'personal_phone')
    op.drop_table('surveyor_client_exclusions')
    # ### end Alembic commands ###
